global:
  scrape_interval: 5s #scrape metrics from targets every 5sample_limit:

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9092']

  - job_name: 'kafka producer'
    static_configs:
      - targets: ["kafka-producer:8081"]
    metrics_path: '/actuator/prometheus'

  - job_name: 'kafka consumer'
    static_configs:
      - targets: ['kafka-consumer:8080']
    metrics_path: '/actuator/prometheus'

  - job_name: 'mysql'
    static_configs:
      - targets: ['database:9104']